{% set name = "isitgr" %}
{% set version = "19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mishakb/ISiTGR/archive/{{ version }}.tar.gz
  sha256: c369dd7a2cb5239f259dad433b7c860be1a9df97d5221284071493e4a1d6190a

build:
  number: 0
  skip: true  # [py2k or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - git
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - six  # TODO: remove for next update
    - mock
    - setuptools  # for an import of pkg_resources
    - sympy >=1.0
    - scipy >=1.0
    - {{ compiler('fortran') }}  # [not win]

test:
  imports:
    - isitgr
  commands:
    - python {{ RECIPE_DIR }}/test_isitgr.py

about:
  home: https://github.com/mishakb/ISiTGR
  license: MIT AND GPL-3.0-or-later
  license_file:
    - LICENSE
    - camb/LICENCE.txt
  summary: Integrated Software in Testing General Relavitity (ISiTGR). A patch of camb to add MG predictions.
  dev_url: https://github.com/mishakb/ISiTGR

extra:
  recipe-maintainers:
    - gqcristhian
    - mishakb
